Repository kkulewski/toktok-frontend, pull requests merged in 2018-12, with the labels that each got.

#24 POST users/Register
  package-lock.json
  src/app/app.module.ts
  src/app/components/navbar/navbar.component.html
  src/app/components/register/register.component.css
  src/app/components/register/register.component.html
  src/app/components/register/register.component.ts
  src/app/models/user.model.ts
  src/app/services/user.service.ts
Labels: feature

#25 Feature/register responses
  src/app/components/register/register.component.html
  src/app/components/register/register.component.ts
  src/app/models/login.result.model.ts
  src/app/models/register.result.model.ts
Labels: feature, improvement

#29 sequence diagrams
  .gitignore
  docs/diagrams/ChooseCanalSequence.asta
  docs/diagrams/ChooseCanalSequence.png
  docs/diagrams/LogInSequence.asta
  docs/diagrams/LogInSequence.png
  docs/diagrams/RegistrationSequence.asta
  docs/diagrams/RegistrationSequence.png
Labels: feature

#28 Login
  package-lock.json
  src/app/app.module.ts
  src/app/components/login/login.component.css
  src/app/components/login/login.component.html
  src/app/components/login/login.component.ts
  src/app/components/navbar/navbar.component.html
  src/app/components/navbar/navbar.component.ts
  src/app/services/user.service.ts
Labels: feature

#30 Add redirect on login and register
  src/app/components/login/login.component.html
  src/app/components/login/login.component.ts
  src/app/components/navbar/navbar.component.html
  src/app/components/navbar/navbar.component.ts
  src/app/components/register/register.component.ts
  src/app/services/user.service.ts
Labels: improvement
